title: zjgtan blog
email: zjgtan@126.com
description: zjgtan的个人博客。
lang: zh_CN
github_username:  zjgtan

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

header_pages:
  - about.md

paginate: 10

lang: 'zh-CN'

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - gen_pages.py
